# Writes models/hpsearch_winner.jld2 from the results of the NePS hyperparameter search
# usage: (from the repo root)   julia --project=hpsearch hpsearch/extract_winner.jl [hpsearch results path]

using JLD2


"""
    Parses a results folder (generated by NePS) to extract the best configuration. Saves a .jld2 containing
    - `model_state`: the weights of the hyperparameter search winner
    - `hp`: a `NamedTuple` of its hyperparameters (to reconstruct the model)
    - `lr`: the learning rate (this is not used in retraining)
    - `neps_config_id`: NePS internal id for the winning hyperparameters
    - `neps_epoch`: the number of epochs the model was trained for
    - `neps_objective`: the final value of the objective function (last validation lost)
"""
function main(dir = isempty(ARGS) ? normpath(joinpath(@__DIR__, "..", "data", "hpsearch", "neps_results")) : ARGS[1])
    id = last(collect(m[1] for m in eachmatch(r"Config ID: (\S+)", read(joinpath(dir, "summary", "best_config.txt"), String)))) # extract config id from the NePS "best_config.txt" summary
    cdir = joinpath(dir, "configs", "config_$id")
    field(file, k) = match(Regex("^$k: (.+)\$", "m"), read(joinpath(cdir, file), String))[1]
    ckpt = load(joinpath(cdir, "checkpoint.jld2"))
    out = joinpath(@__DIR__, "..", "models", "hpsearch_winner.jld2")
    jldsave(out; model_state = ckpt["model_state"], hp = ckpt["hp"], lr = parse(Float64, field("config.yaml", "learning_rate")),
            neps_config_id = id, neps_epochs = parse(Int, field("config.yaml", "epoch")),
            neps_objective = parse(Float64, field("report.yaml", "objective_to_minimize")))
    println("config $id -> $out")
end

main()
